### ISSUE TITLE
Validations of XML component for attachments . 

### ISSUE THREAD

**Issue by abrodeur** [elasticio/xml-component#5]
1. A user should be able to use the XML component to transform attachment on the elastic.io system into a json string. 
2. The component should select all attachments that match a regex expression for the filename. 
3. These changes should have no effect on existing functionality.  

The code for the change are in the two pull request( https://github.com/elasticio/xml-component/pull/3 , https://github.com/elasticio/xml-component/pull/4 ).

Basic test flow( it is in organisation so you may need to request me to join my organisations) : https://app.elastic.io/c/5b8f99106d19500012492091#/w/5b8f99106d19500012492092/designer/5bbb5aa4bc41580010c0e7be/draft

**Comment by shulkaolka** [comment]
https://github.com/elasticio/xml-component/pull/3 was closed (is part of PR4). Need to be tested https://github.com/elasticio/xml-component/pull/4

**Comment by stas-fomenko** [comment]
What behavior is expected when:

**Comment by stas-fomenko** [comment]
@abrodeur 
- [ ] Can you please specify expected behavior (I also need this to create proper tests) of "Action: XML Attachment to JSON", what is expected when:
- field "Pattern to Match Files" is filled with invalid value
-  "Pattern to Match Files" field is filled with valid value
-  "Pattern to Match Files" field is blank


- [ ] And also add this into Readme.md

- [ ] Add Descriptions for all three actions
![image](https://user-images.githubusercontent.com/36419533/49023980-11797000-f1a1-11e8-9a05-bc3284b5a418.png)

**Comment by stas-fomenko** [comment]
@zubairov maybe you as PO have any thoughts regarding first item? ☝️

**Comment by zubairov** [comment]
> field "Pattern to Match Files" is filled with invalid value

Ideally, we should react immediately and provide user feedback on that (show error in UI), currently, it is not possible (missing field type for RegExp, issue created https://github.com/elasticio/platform/issues/539) so we need to react on the earliest possible moment - **at component start time**

> "Pattern to Match Files" field is filled with valid value

Work as expected

> "Pattern to Match Files" field is blank

Process all attachments

@abrodeur @jhorbulyk objections?
